import {useEffect,useRef,useState} from 'react';
import {ShoppingBag,LayoutDashboard,Package,Tags,Boxes,ShoppingCart,Users,CreditCard,Sparkles,Plus,Search,ArrowUpRight,LogOut,X} from 'lucide-react';
import {api,ApiError} from './api';
import {cents} from './forms';
import {Data,Product,Customer,Category,Detail,Order,money,orderNo} from './types';
type Page='dashboard'|'products'|'categories'|'inventory'|'orders'|'customers'|'payments';
type Editor={kind:'product'|'category'|'customer'|'stock';id?:number;values:Record<string,string>};
const pages:{id:Page;label:string;icon:typeof Package}[]=[{id:'dashboard',label:'Overview',icon:LayoutDashboard},{id:'products',label:'Products',icon:Package},{id:'categories',label:'Categories',icon:Tags},{id:'inventory',label:'Inventory',icon:Boxes},{id:'orders',label:'Orders',icon:ShoppingCart},{id:'customers',label:'Customers',icon:Users},{id:'payments',label:'Payments',icon:CreditCard}];
function pageFromHash():Page {const id=location.hash.slice(1);return pages.some(p=>p.id===id)?id as Page:'dashboard';}
export default function App(){
 const [user,setUser]=useState<{name:string}|null>(null),[starting,setStarting]=useState(true),[data,setData]=useState<Data|null>(null);
 const [page,setPage]=useState<Page>(pageFromHash),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [editor,setEditor]=useState<Editor|null>(null),[aiDraft,setAiDraft]=useState(''),[aiNotice,setAiNotice]=useState('');
 const [detail,setDetail]=useState<Detail|null>(null),[newOrder,setNewOrder]=useState(false),[customer,setCustomer]=useState(''),[cart,setCart]=useState<{product_id:string;quantity:number}[]>([{product_id:'',quantity:1}]);
 const requestKey=useRef(crypto.randomUUID());const paymentKeys=useRef<Record<string,string>>({});
 async function refresh(){setData(await api<Data>('/data'));}
 useEffect(()=>{const change=()=>{setPage(pageFromHash());setQuery('');};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{void(async()=>{try{setUser(await api('/me'));await refresh();}catch(e){if(!(e instanceof ApiError&&e.status===401))setError((e as Error).message);}finally{setStarting(false);}})();},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){if(e instanceof ApiError&&e.status===401){setUser(null);setData(null);}setError((e as Error).message);}finally{setBusy(false);}}
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(async()=>{setUser(await api('/login','POST',Object.fromEntries(f)));await refresh();});}
 function openEditor(kind:Editor['kind'],item?:Product|Customer|Category){
  setError('');setAiDraft('');setAiNotice('');
  let values:Record<string,string>={};
  if(kind==='product'){
   const p=item as Product|undefined;
   values={name:p?.name||'',sku:p?.sku||'',category_id:String(p?.category_id||data?.categories[0]?.id||''),facts:p?.facts||'',description:p?.description||'',price:p?(p.price_cents/100).toFixed(2):'0.00',low_stock_threshold:String(p?.low_stock_threshold??5),active:p?.active===false||p?.active===0?'false':'true'};
  }else if(kind==='customer'){const c=item as Customer|undefined;values={name:c?.name||'',email:c?.email||'',phone:c?.phone||'',address:c?.address||''};}
  else if(kind==='category')values={name:item?.name||''};
  else values={delta:'',reason:''};
  setEditor({kind,id:item?.id,values});
 }
 function field(name:string,value:string){setEditor(e=>e?{...e,values:{...e.values,[name]:value}}:e);}
 async function save(e:React.FormEvent){e.preventDefault();if(!editor)return;await run(async()=>{
  const {kind,id,values:v}=editor;let payload:unknown=v;
  if(kind==='product')payload={name:v.name,sku:v.sku,category_id:Number(v.category_id),facts:v.facts,description:v.description,price_cents:cents(v.price),low_stock_threshold:Number(v.low_stock_threshold),active:v.active==='true'};
  if(kind==='stock')payload={delta:Number(v.delta),reason:v.reason};
  const path=kind==='stock'?'/products/'+id+'/stock':'/'+({product:'products',category:'categories',customer:'customers'} as const)[kind]+(id?'/'+id:'');
  await api(path,kind==='stock'||!id?'POST':'PUT',payload);setEditor(null);setNotice('Changes saved.');await refresh();
 });}
 async function generate(){if(!editor)return;
  const external=data?.ai_provider==='openai';
  if(external&&!confirm('Share this product name and its facts with OpenAI to generate a draft?'))return;
  await run(async()=>{const result=await api<{description:string;notice:string}>('/ai/description','POST',{name:editor.values.name,facts:editor.values.facts,confirm_external:external});setAiDraft(result.description);setAiNotice(result.notice);});
 }
 async function viewOrder(id:number){await run(async()=>setDetail(await api<Detail>('/orders/'+id)));}
 async function orderAction(action:string,outcome?:string){if(!detail)return;const id=detail.order.id;
  if(['refund','cancel','fulfill'].includes(action)&&!confirm(action+' '+orderNo(id)+'?'))return;
  await run(async()=>{
   const key=id+':'+outcome;
   const body=action==='payment'?{outcome,request_key:paymentKeys.current[key]||=(crypto.randomUUID())}:{};
   await api('/orders/'+id+'/'+action,'POST',body);delete paymentKeys.current[key];
   setDetail(await api('/orders/'+id));await refresh();setNotice('Order updated.');
  });
 }
 function startOrder(){requestKey.current=crypto.randomUUID();setCustomer(String(data?.customers[0]?.id||''));setCart([{product_id:'',quantity:1}]);setNewOrder(true);setError('');}
 async function createOrder(e:React.FormEvent){e.preventDefault();await run(async()=>{
  const o=await api<Order>('/orders','POST',{request_key:requestKey.current,customer_id:Number(customer),items:cart.map(l=>({product_id:Number(l.product_id),quantity:l.quantity}))});
  setNewOrder(false);await refresh();setDetail(await api('/orders/'+o.id));setNotice('Order created and stock reserved.');
 });}
 const msg=<>{error&&<div className="alert error" role="alert">{error}</div>}{notice&&<div className="alert success" role="status">{notice}</div>}</>;
 if(starting)return <div className="loading">Loading Commerce Desk…</div>;
 if(!user)return <div className="login"><div className="login-brand"><ShoppingBag size={42}/><h1>Commerce Desk<span>Your store, in order.</span></h1><p>Catalogue, inventory and orders in one workspace.</p><small>Portfolio application · simulated payments</small></div><form onSubmit={login}><p className="eyebrow">ADMIN ACCESS</p><h2>Welcome back</h2><p>Sign in to manage your store.</p>{msg}<label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button className="primary" disabled={busy}>Sign in <ArrowUpRight size={18}/></button><small>Create your administrator with the setup command in the README.</small></form></div>;
 const products=data?.products||[],orders=data?.orders||[];
 const matching=(s:string)=>s.toLowerCase().includes(query.toLowerCase());
 const net=orders.filter(o=>['paid','fulfilled'].includes(o.status)).reduce((n,o)=>n+Number(o.total_cents),0);
 const low=products.filter(p=>Boolean(p.active)&&p.stock<=p.low_stock_threshold);
 const orderTable=(rows:Order[])=><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th><th>Created</th><th/></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>{orderNo(o.id)}</b></td><td>{o.customer_name}</td><td><span className={'badge '+o.status}>{o.status}</span></td><td>{money(o.total_cents)}</td><td>{new Date(o.created_at).toLocaleDateString()}</td><td><button disabled={busy} className="text-button" onClick={()=>void viewOrder(o.id)}>View →</button></td></tr>)}</tbody></table>{rows.length===0&&<Empty text="No matching orders. Create an order to begin."/>}</div>;
 return <div className="shell"><aside><a className="brand" href="#dashboard"><span><ShoppingBag/></span><b>Commerce<br/>Desk</b></a><p className="nav-label">WORKSPACE</p><nav>{pages.map(p=><a key={p.id} href={'#'+p.id} className={page===p.id?'active':''}><p.icon size={19}/>{p.label}</a>)}</nav><div className="sidebar-note"><Sparkles size={20}/><b>Product copy, assisted</b><p>Generate a draft.<br/>Make it your own.</p></div><div className="profile"><span>{user.name.slice(0,1)}</span><div><b>{user.name}</b><small>Administrator</small></div><button aria-label="Sign out" disabled={busy} onClick={()=>void run(async()=>{await api('/logout','POST');setUser(null);setData(null);setDetail(null);setEditor(null);setNewOrder(false);})}><LogOut size={18}/></button></div></aside>
 <main><header><span>Store operations <span className="slash">/</span> {pages.find(p=>p.id===page)?.label}</span><span className="sandbox">SIMULATED PAYMENTS</span></header><div className="content"><div className="page-title"><div><p className="eyebrow">COMMERCE DESK</p><h1>{page==='dashboard'?'Store overview':pages.find(p=>p.id===page)?.label}</h1><p>{({dashboard:'A clear view of what needs your attention.',products:'Manage your catalogue and product copy.',categories:'Keep your catalogue organised.',inventory:'Track available stock and every adjustment.',orders:'From a new order to fulfilment.',customers:'Your customer directory.',payments:'Test payment outcomes. No real money moves.'})[page]}</p></div><div className="actions"><button disabled={busy} onClick={()=>void run(refresh)}>Refresh</button>{['dashboard','orders'].includes(page)?<button className="primary" disabled={busy||!data} onClick={startOrder}><Plus size={18}/>Create order</button>:['products','categories','customers'].includes(page)?<button className="primary" disabled={busy||!data} onClick={()=>openEditor(page==='products'?'product':page==='categories'?'category':'customer')}><Plus size={18}/>Add {page==='categories'?'category':page.slice(0,-1)}</button>:null}</div></div>
 {msg}{!data?<Empty text="Data could not be loaded. Use Refresh to try again."/>:<>
 {page==='dashboard'?<><section className="stats"><Stat label="Simulated net sales" value={money(net)} note="Paid and fulfilled orders"/><Stat label="Orders to fulfil" value={String(orders.filter(o=>o.status==='paid').length)} note="Payment received"/><Stat label="Active products" value={String(products.filter(p=>p.active).length)} note="Available in your catalogue"/><Stat label="Low stock" value={String(low.length)} note="At or below the stock threshold" highlight/></section><div className="overview-grid"><section className="panel"><div className="panel-title"><h2>Recent orders</h2><a href="#orders">View all →</a></div>{orderTable(orders.slice(0,6))}</section><section className="panel attention"><p className="eyebrow">NEEDS ATTENTION</p><h2>Keep your shelves ready.</h2><p>{low.length?low.length+' products are running low.':'Your active products have healthy stock.'}</p>{low.slice(0,4).map(p=><div className="stock-row" key={p.id}><span><b>{p.name}</b><small>{p.sku}</small></span><strong>{p.stock}<small>left</small></strong></div>)}<a className="dark-link" href="#inventory">Manage inventory <ArrowUpRight size={18}/></a></section></div><section className="panel flow"><div><h2>Order progress</h2><p>Current status of all orders</p></div>{['pending','paid','fulfilled','cancelled','refunded'].map(s=><div key={s}><strong>{orders.filter(o=>o.status===s).length}</strong><span>{s}</span></div>)}</section></>:<>
 <div className="toolbar"><label className="search"><Search size={18}/><input aria-label="Search current page" placeholder={'Search '+page+'…'} value={query} onChange={e=>setQuery(e.target.value)}/></label><span>AUD · {page==='payments'?'Latest 100 payment attempts':page==='inventory'?'Available stock excludes reserved orders':'Saved to your database'}</span></div>
 {page==='orders'&&<section className="panel">{orderTable(orders.filter(o=>matching(orderNo(o.id)+' '+o.customer_name+' '+o.status)))}</section>}
 {page==='products'&&<section className="panel table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{products.filter(p=>matching(p.name+p.sku+p.category_name)).map(p=><tr key={p.id}><td><div className="product-cell"><span className="product-icon"><Package size={22}/></span><span><b>{p.name}</b><small>{p.sku}</small></span></div></td><td>{p.category_name}</td><td>{money(p.price_cents)}</td><td><span className={p.stock<=p.low_stock_threshold?'stock-low':''}>{p.stock} available</span></td><td><span className={'badge '+(p.active?'paid':'cancelled')}>{p.active?'Active':'Archived'}</span></td><td><button onClick={()=>openEditor('product',p)}>Edit</button></td></tr>)}</tbody></table>{!products.length&&<Empty text="Add your first product. Opening stock is added in Inventory."/>}</section>}
 {page==='categories'&&<section className="panel table-wrap"><table><thead><tr><th>Category</th><th>Products</th><th/></tr></thead><tbody>{data.categories.filter(c=>matching(c.name)).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{products.filter(p=>p.category_id===c.id).length}</td><td className="actions"><button onClick={()=>openEditor('category',c)}>Edit</button><button disabled={busy} onClick={()=>{if(confirm('Delete '+c.name+'?'))void run(async()=>{await api('/categories/'+c.id,'DELETE');await refresh();});}}>Delete</button></td></tr>)}</tbody></table>{!data.categories.length&&<Empty text="Create a category before adding products."/>}</section>}
 {page==='customers'&&<section className="panel table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Orders</th><th/></tr></thead><tbody>{data.customers.filter(c=>matching(c.name+c.email)).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.email}</td><td>{c.phone||'—'}</td><td>{orders.filter(o=>o.customer_id===c.id).length}</td><td><button onClick={()=>openEditor('customer',c)}>Edit</button></td></tr>)}</tbody></table>{!data.customers.length&&<Empty text="Add a customer before creating an order."/>}</section>}
 {page==='inventory'&&<><section className="panel table-wrap"><table><thead><tr><th>Product</th><th>Available</th><th>Low-stock threshold</th><th/></tr></thead><tbody>{products.filter(p=>matching(p.name+p.sku)).map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.sku}</small></td><td className={p.stock<=p.low_stock_threshold?'stock-low':''}>{p.stock}</td><td>{p.low_stock_threshold}</td><td><button onClick={()=>openEditor('stock',p)}>Adjust stock</button></td></tr>)}</tbody></table></section><section className="panel"><div className="panel-title"><h2>Stock movement history</h2><span>Latest 100</span></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Change</th><th>After</th><th>Reason</th><th>Date</th></tr></thead><tbody>{data.movements.filter(m=>matching(m.product_name+m.reason)).map(m=><tr key={m.id}><td>{m.product_name}</td><td>{m.delta>0?'+':''}{m.delta}</td><td>{m.stock_after}</td><td>{m.reason}</td><td>{new Date(m.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section></>}
 {page==='payments'&&<section className="panel table-wrap"><table><thead><tr><th>Reference</th><th>Order</th><th>Outcome</th><th>Amount</th><th>Date</th></tr></thead><tbody>{data.payments.filter(p=>matching(p.reference+orderNo(p.order_id)+p.outcome)).map(p=><tr key={p.id}><td><small>{p.reference}</small></td><td><button className="text-button" onClick={()=>void viewOrder(p.order_id)}>{orderNo(p.order_id)}</button></td><td><span className={'badge '+p.outcome}>{p.outcome}</span></td><td>{money(p.amount_cents)}</td><td>{new Date(p.created_at).toLocaleString()}</td></tr>)}</tbody></table>{!data.payments.length&&<Empty text="Open an order to simulate a successful or failed payment."/>}</section>}
 </>}
 </>}</div><footer className="footer">Commerce Desk <span>Portfolio edition · AUD · All payments are simulated</span></footer></main>
 {editor&&<Modal title={editor.kind==='stock'?'Adjust stock':(editor.id?'Edit ':'Add ')+editor.kind} close={()=>setEditor(null)} busy={busy}><form onSubmit={save}>{error&&<div className="alert error" role="alert">{error}</div>}
 {Object.entries(editor.values).map(([key,value])=><label key={key}>{({category_id:'Category',facts:'Verified product facts',price:'Price (AUD)',low_stock_threshold:'Low-stock threshold',active:'Catalogue status',delta:'Stock change (e.g. 10 or -2)'})[key]||key.charAt(0).toUpperCase()+key.slice(1)}
 {key==='category_id'?<select required value={value} onChange={e=>field(key,e.target.value)}><option value="">Choose a category</option>{data?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:key==='active'?<select value={value} onChange={e=>field(key,e.target.value)}><option value="true">Active</option><option value="false">Archived</option></select>:['facts','description','address'].includes(key)?<textarea rows={key==='description'?5:3} value={value} required={key==='facts'} maxLength={key==='facts'?5000:key==='description'?10000:1000} onChange={e=>field(key,e.target.value)}/>:<input value={value} required={!['phone'].includes(key)} type={key==='email'?'email':['delta','low_stock_threshold','price'].includes(key)?'number':'text'} step={key==='price'?'0.01':['delta','low_stock_threshold'].includes(key)?'1':undefined} min={['price','low_stock_threshold'].includes(key)?0:undefined} onChange={e=>field(key,e.target.value)}/>}</label>)}
 {editor.kind==='product'&&<div className="ai-box"><h3><Sparkles size={18}/>Description assistant</h3><p>Use the verified facts above. Review the draft before saving.</p><button type="button" disabled={busy||!editor.values.name||editor.values.facts.length<10} onClick={()=>void generate()}>{busy?'Please wait…':data?.ai_provider==='openai'?'Generate AI draft':'Generate template draft'}</button>{aiDraft&&<><p className="draft">{aiDraft}</p><small>{aiNotice}</small><button type="button" onClick={()=>{if(editor.values.description&&!confirm('Replace the current description with this draft?'))return;field('description',aiDraft);}}>Use this draft</button></>}</div>}
 <button className="primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></form></Modal>}
 {newOrder&&<Modal title="Create order" close={()=>setNewOrder(false)} busy={busy}><form onSubmit={createOrder}>{error&&<div className="alert error" role="alert">{error}</div>}<label>Customer<select required value={customer} onChange={e=>{setCustomer(e.target.value);requestKey.current=crypto.randomUUID();}}><option value="">Select customer</option>{data?.customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select></label><h3>Order items</h3>{cart.map((line,index)=><div className="cart-row" key={index}><label>Product<select required value={line.product_id} onChange={e=>{setCart(c=>c.map((l,i)=>i===index?{...l,product_id:e.target.value}:l));requestKey.current=crypto.randomUUID();}}><option value="">Choose product</option>{products.filter(p=>p.active).map(p=><option disabled={p.stock<1} key={p.id} value={p.id}>{p.name} · {money(p.price_cents)} · {p.stock} left</option>)}</select></label><label>Qty<input type="number" min={1} max={1000} required value={line.quantity} onChange={e=>{setCart(c=>c.map((l,i)=>i===index?{...l,quantity:Number(e.target.value)}:l));requestKey.current=crypto.randomUUID();}}/></label><button type="button" aria-label="Remove item" disabled={cart.length===1} onClick={()=>{setCart(c=>c.filter((_,i)=>i!==index));requestKey.current=crypto.randomUUID();}}><X size={17}/></button></div>)}<button type="button" disabled={cart.length>=50} onClick={()=>{setCart(c=>[...c,{product_id:'',quantity:1}]);requestKey.current=crypto.randomUUID();}}>+ Add item</button><div className="order-total"><span>Estimated total</span><strong>{money(cart.reduce((n,l)=>n+(products.find(p=>p.id===Number(l.product_id))?.price_cents||0)*l.quantity,0))}</strong></div><p>Stock is reserved when you create the order. Prices and availability are checked again by the server.</p><button className="primary" disabled={busy}>{busy?'Creating…':'Create order'}</button></form></Modal>}
 {detail&&<Modal title={orderNo(detail.order.id)} close={()=>setDetail(null)} busy={busy}>{error&&<div className="alert error" role="alert">{error}</div>}<div className="order-heading"><span><b>{detail.order.customer_name}</b><small>{detail.order.customer_email}</small></span><span className={'badge '+detail.order.status}>{detail.order.status}</span></div>{detail.items.map(i=><div className="order-item" key={i.id}><span><b>{i.name}</b><small>{i.quantity} × {money(i.unit_price_cents)} · {i.sku}</small></span><strong>{money(i.quantity*i.unit_price_cents)}</strong></div>)}<div className="order-total"><span>Total</span><strong>{money(detail.order.total_cents)}</strong></div><div className="ai-box"><h3>Payment simulation</h3><p>No card details. No real charges.</p><div className="actions">{detail.order.status==='pending'&&<><button disabled={busy} className="primary" onClick={()=>void orderAction('payment','success')}>Simulate success</button><button disabled={busy} onClick={()=>void orderAction('payment','failed')}>Simulate failure</button></>}{detail.order.status==='paid'&&<><button disabled={busy} className="primary" onClick={()=>void orderAction('fulfill')}>Mark fulfilled</button><button disabled={busy} onClick={()=>void orderAction('refund')}>Simulate refund</button></>}{detail.order.status==='pending'&&<button disabled={busy} onClick={()=>void orderAction('cancel')}>Cancel order</button>}</div></div><h3>Payment history</h3>{detail.payments.length?detail.payments.map(p=><div className="order-item" key={p.id}><span className={'badge '+p.outcome}>{p.outcome}</span><span>{money(p.amount_cents)}<small>{new Date(p.created_at).toLocaleString()}</small></span></div>):<p>No payment attempts yet.</p>}</Modal>}
 </div>;
}
function Empty({text}:{text:string}){return <div className="empty"><Package size={28}/><p>{text}</p></div>;}
function Stat({label,value,note,highlight=false}:{label:string;value:string;note:string;highlight?:boolean}){return <article className={'stat '+(highlight?'highlight':'')}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;}
function Modal({title,close,busy,children}:{title:string;close:()=>void;busy:boolean;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} onCancel={e=>{e.preventDefault();if(!busy)close();}}><div className="modal-heading"><h2>{title}</h2><button disabled={busy} aria-label="Close dialog" onClick={close}><X size={20}/></button></div>{children}</dialog>;
}

